name: Deploy EJS Template

on:
  push:
    branches:
      - main # Change to your main branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install EJS CLI
      run: npm install -g ejs-cli

    - name: Precompile EJS to HTML
      run: ejs-cli ./views/index.ejs -o ./public/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public
        publish_branch: gh-pages
